### PR TITLE
feat(cdn): deliver friendly CORP headers

### PR DESCRIPTION
**Pull request by trieloff**

### CODE REVIEW

**Comment by kptdobe** [comment]
Thanks @trieloff. 

Context: COOP and COEP is the new trend and is going to be defined everywhere.
To reproduce the issue:
- go to https://www.aem.live/home?rum=on
- in Chrome, edit the Headers of the `home.html` request and add `Cross-Origin-Embedder-Policy: require-corp`
-  reload the page, you'll get some obscur  `(net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 201` CORS issue which blocks the execution of our RUM collection

2 options: 
1. we can ask the sites consuming our rum-js to remove the headers
2. add the `Cross-Origin-Resource-Policy: cross-origin` header to all rum.hlx.page responses

Since the trend seems to be to use those headers, we should follow the trend. I have created a proxy of the rum requests that adds the header and it fixes the issue. But I do not know if this has other consequences.

More details about the headers:
- https://resourcepolicy.fyi/
- https://docs.google.com/document/d/1zDlfvfTJ_9e8Jdc8ehuV4zMEu9ySMCiTGMS9y0GU92k/edit

**Comment by trieloff** [comment]
@kptdobe try with `helix-rum-collector-ci.edgecompute.app` instead of `rum.hlx.page` to see the new code in action.

**Comment by kptdobe** [comment]
Tested. I see the header for the GET requests but not for the POST requests.

**Comment by kptdobe** [comment]
The behavior is weird because the POSTs succeed (201) but browser does not process the response

image

**Comment by trieloff** [comment]
Do you think it is an issue? The POST response is never read by the browser, and the `rum collected` message is more for my own (and `curl`'s) edification than it is functional.

**Comment by kptdobe** [comment]
Would not be an issue if the console wouldn't be full of error messages: 

image

**Comment by trieloff** [comment]
Ok, I'll add the header to suppress this message, if we can keep the `console.debug` in turn.

**Review by bosschaert — APPROVED** [review]
LGTM 👍

**Pull request merged**
