### PR TITLE
feat: allow cwv to be omitted

### PR DESCRIPTION
**Pull request by kptdobe**
Relax the API and allow `cwv` to be omitted

### CODE REVIEW

**Comment by trieloff** [comment]
What's the point of omitting `cwv` and logging nothing?

**Review by trieloff — CHANGES_REQUESTED** [review]
You need to adjust the post-deploy tests, too. But I'm not clear what the value of an empty log would be.

**Comment by kptdobe** [comment]
This is the request for page view, no `cwv` provided. Since `cwv` are not always captured, at least we know if a page has been loaded and we can ensure the `weight` is respected.

**Review by trieloff — APPROVED** [review]

**Comment by kptdobe** [comment]
An empty log just records the `weight` and the `id`.

**Comment by trieloff** [comment]
One more failing test... – you can just remove the failing test case.

**Comment by kptdobe** [comment]
Desperately trying to fix the test... but without proper unit tests, hard to guess what happens.

**Comment by kptdobe** [comment]
Ok, removed the failing test, green now.

**Pull request merged**
