### PR TITLE
Change status code to 204 to match spec

### PR DESCRIPTION
**Pull request by ieb**
The spec https://w3c.github.io/beacon/#sendbeacon-method recommends using an 204 for beacon responses with no bodies.

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi @ieb , when I run this through the unit tests, I'm getting the following error:

```
TypeError: Response constructor: Invalid response status code 204
    at webidl.errors.exception (node:internal/deps/undici/undici:1265:14)
    at initializeResponse (node:internal/deps/undici/undici:6845:31)
    at new Response (node:internal/deps/undici/undici:6654:9)
    at Object.main (file:///Users/david/clones/helix-rum-collector/src/index.mjs:95:22)
    at Context.<anonymous> (file:///Users/david/clones/helix-rum-collector/test/index.test.mjs:39:32)
    at callFn (/Users/david/clones/helix-rum-collector/node_modules/mocha/lib/runnable.js:366:21)
    at Runnable.run (/Users/david/clones/helix-rum-collector/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/Users/david/clones/helix-rum-collector/node_modules/mocha/lib/runner.js:666:10)
    at /Users/david/clones/helix-rum-collector/node_modules/mocha/lib/runner.js:789:12
    at next (/Users/david/clones/helix-rum-collector/node_modules/mocha/lib/runner.js:581:14) {stack: 'TypeError: Response constructor: Invalid resp…ctor/node_modules/mocha/lib/runner.js:581:14)', message: 'Response constructor: Invalid response status code 204'}
```

**Comment by ieb** [comment]
Should be fixed now. Caused by strict checks at https://github.com/nodejs/undici/blob/3a77cbb471b76175898d8b094beb9b40ceadd671/lib/fetch/response.js#L477

**Comment by bosschaert** [comment]
The response body doesn't contain the text `rum collected.` any more. I wonder if that is desirable. 

@trieloff thoughts?

**Comment by trieloff** [comment]
So this PR changed an HTTP 201 Created (which arguably was correct, because a data entry has been created) into an HTTP 204 No Content (which clearly was not correct, because there was a response body) when the tests failed, the way to address this was to remove the response body entirely. 

To me this looks like a breaking change motivated by little more than aesthetics and I'd rather keep it the way it was before.

**Pull request closed without merging**
