### PR TITLE
fix(log): Limit time-padding value to 1 day

### PR DESCRIPTION
**Pull request by bosschaert**
## Related Issues

Fixes: #225

### CODE REVIEW

**Comment by bosschaert** [comment]
I limited the padding value to an hour for now, as its added to the current hour. @trieloff let me know if you disagree.

**Review by trieloff — CHANGES_REQUESTED** [review]
I'd go with a simple `max(+24h, caluclated)` so that we can analyze this a bit easier. With the rollover approach I have no way to see this in the data.

**Comment by bosschaert** [comment]
> I'd go with a simple `max(+24h, caluclated)` so that we can analyze this a bit easier. With the rollover approach I have no way to see this in the data.

I've made this change now but with `min(+24h, calculated)` which I what I think you meant 😄

**Review by trieloff — APPROVED** [review]

**Pull request merged**
