### PR TITLE
feat(utils): Update extraction of hostname from X-Forwarded-Host to favour AEM hostname

### PR DESCRIPTION
**Pull request by bosschaert**
Fixes: #255

### CODE REVIEW

**Comment by cziegeler** [comment]
@bosschaert Can we please add a test case for this url "author-p12334-e56789.adobeaemcloud.net" and check that it matches?

**Comment by bosschaert** [comment]
Thanks @cziegeler I expanded the matching list to include `adobeaemcloud` and added the test.

**Review by cziegeler — APPROVED** [review]
thanks!

**Review by trieloff — APPROVED** [review]

**Pull request merged**
